name: Gihub Actions

# main 브랜치에 푸쉬될 때 아래 job 실행
on:
  push:
    branches:
      - main

# 하나의 Workflow는 1개 이상의 Job
# 여러 Job은 기본적으로 병렬 수행
jobs:
  # Job 식별 id
  My-Deploy-Job:
    runs-on: ubuntu-latest
    steps:
      - name : EC2 SSH 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd /home/ubuntu/ho-commerce
            git pull origin main
            ./gradlew clean build -x test
            sudo fuser -k -n tcp 8080 || true
            
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &

